USE db_geos;

DROP TABLE IF EXISTS DASHBOARD;
DROP TABLE IF EXISTS AGENDA_BATERIA;
DROP TABLE IF EXISTS AGENDA;
DROP TABLE IF EXISTS AFILIACION;
DROP TABLE IF EXISTS ACTIVIDADECONOMICA;
DROP TABLE IF EXISTS SOLICITUD_TRABAJADOR_EXAMEN;
DROP TABLE IF EXISTS COMENTARIOS_SOLICITUD;
DROP TABLE IF EXISTS SOL_EMP_TRA;
DROP TABLE IF EXISTS EXAMENES;
DROP TABLE IF EXISTS BATERIA;
DROP TABLE IF EXISTS ESTADOS_SOLICITUD;
DROP TABLE IF EXISTS SOLICITUD;
DROP TABLE IF EXISTS TRABAJADOR;
DROP TABLE IF EXISTS ARCHIVOS;
DROP TABLE IF EXISTS EMPLEADOR;
DROP TABLE IF EXISTS PRESTADOR;
DROP TABLE IF EXISTS USUARIOS;


-- Usuarios
CREATE TABLE USUARIOS (
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    RUT VARCHAR(255) UNIQUE NOT NULL,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    REGION VARCHAR(255) NOT NULL,
    COMUNA VARCHAR(255) NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FONO VARCHAR(255) NOT NULL,
    CLAVE VARCHAR(255) NOT NULL,
    VIGENTE BOOLEAN NOT NULL
);

-- Prestador
CREATE TABLE PRESTADOR (
    IDPRESTADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    FONO VARCHAR(255) NOT NULL,
    CONTACTO VARCHAR(255) NOT NULL,
    CORREO VARCHAR(255) NOT NULL,
    REGION VARCHAR(255) NOT NULL,
    COMUNA VARCHAR(255) NOT NULL,
    FECHAINICIO DATE NOT NULL,
    FECHAFIN DATE NOT NULL,
    VIGENTE BOOLEAN NOT NULL
);

-- Empleador
CREATE TABLE EMPLEADOR (
    IDEMPLEADOR INT PRIMARY KEY AUTO_INCREMENT,
    RUT VARCHAR(255) UNIQUE NOT NULL,
    RAZONSOCIAL VARCHAR(255) NOT NULL,
    CONTACTO VARCHAR(255) NOT NULL,
    FONO VARCHAR(255) NOT NULL,
    CORREO VARCHAR(255) NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    REGION VARCHAR(255) NOT NULL,
    COMUNA VARCHAR(255) NOT NULL,
    CODIGOAE VARCHAR(255) NOT NULL,
    VIGENTE BOOLEAN NOT NULL
);


-- Archivos
CREATE TABLE ARCHIVOS (
    ID_ARCHIVO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    TIPO_ARCHIVO VARCHAR(255) NOT NULL
);

-- Trabajador
CREATE TABLE TRABAJADOR (
    IDTRABAJADOR INT PRIMARY KEY AUTO_INCREMENT,
    RUT VARCHAR(255) UNIQUE NOT NULL,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    VIGENTE BOOLEAN NOT NULL,
    IDEMPLEADOR INT,
    ID_ARCHIVO INT,
    FOREIGN KEY (IDEMPLEADOR) REFERENCES EMPLEADOR(IDEMPLEADOR),
    FOREIGN KEY (ID_ARCHIVO) REFERENCES ARCHIVOS(ID_ARCHIVO)
);

-- Estados_Solicitud
CREATE TABLE ESTADOS_SOLICITUD (
    ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ESTADO VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL
);


-- Solicitud
CREATE TABLE SOLICITUD (
    IDSOLICITUD INT PRIMARY KEY AUTO_INCREMENT,
    FECHASOLICITUD DATE NOT NULL,
    IDUSUARIO INT,
    IDEMPLEADOR INT,
    NOMBRE VARCHAR(255) NOT NULL,
    RAZON VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
    IDPRESTADOR INT,
    DIRECCION_PRESTADOR VARCHAR(255),
    ID_ESTADO INT,
    ID_ARCHIVO INT,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO),
    FOREIGN KEY (IDEMPLEADOR) REFERENCES EMPLEADOR(IDEMPLEADOR),
    FOREIGN KEY (IDPRESTADOR) REFERENCES PRESTADOR(IDPRESTADOR),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS_SOLICITUD(ID_ESTADO),
    FOREIGN KEY (ID_ARCHIVO) REFERENCES ARCHIVOS(ID_ARCHIVO)
);

-- Bateria
CREATE TABLE BATERIA (
    IDBATTERIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    RECOMENDACION VARCHAR(255) NOT NULL,
    JORNADA VARCHAR(255) NOT NULL,
    VIGENTE BOOLEAN NOT NULL,
    IDPRESTADOR INT,
    FOREIGN KEY (IDPRESTADOR) REFERENCES PRESTADOR(IDPRESTADOR)
);


-- Examenes
CREATE TABLE EXAMENES (
    IDEXAMEN INT PRIMARY KEY AUTO_INCREMENT,
    IDBATTERIA INT,
    NOMBRE VARCHAR(255) NOT NULL,
    EVALUACION VARCHAR(255) NOT NULL,
    FOREIGN KEY (IDBATTERIA) REFERENCES BATERIA(IDBATTERIA)
);


-- Sol_Emp_Tra
CREATE TABLE SOL_EMP_TRA (
    IDSOLEMPTRA INT PRIMARY KEY AUTO_INCREMENT,
    IDSOLICITUD INT,
    IDEMPLEADOR INT,
    IDTRABAJADOR INT,
    FOREIGN KEY (IDSOLICITUD) REFERENCES SOLICITUD(IDSOLICITUD),
    FOREIGN KEY (IDEMPLEADOR) REFERENCES EMPLEADOR(IDEMPLEADOR),
    FOREIGN KEY (IDTRABAJADOR) REFERENCES TRABAJADOR(IDTRABAJADOR)
);

-- Comentarios_Solicitud
CREATE TABLE COMENTARIOS_SOLICITUD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHACOMENTARIO DATE NOT NULL,
    TEXTO TEXT NOT NULL,
    IDSOLICITUD INT,
    FOREIGN KEY (IDSOLICITUD) REFERENCES SOLICITUD(IDSOLICITUD)
);

-- Solicitud_Trabajador_Examen
CREATE TABLE SOLICITUD_TRABAJADOR_EXAMEN (
    IDAGENDA INT PRIMARY KEY AUTO_INCREMENT,
    IDSOLICITUD INT,
    IDTRABAJADOR INT,
    FOREIGN KEY (IDSOLICITUD) REFERENCES SOLICITUD(IDSOLICITUD),
    FOREIGN KEY (IDTRABAJADOR) REFERENCES TRABAJADOR(IDTRABAJADOR)
);

-- Actividad_Economica
CREATE TABLE ACTIVIDADECONOMICA (
    CODIGOAE VARCHAR(255) PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL
);

-- Afiliacion
CREATE TABLE AFILIACION (
    IDAFILIACION INT PRIMARY KEY AUTO_INCREMENT,
    FECHACONSULTA DATE NOT NULL,
    AFILIADO BOOLEAN NOT NULL,
    IDEMPLEADOR INT,
    FOREIGN KEY (IDEMPLEADOR) REFERENCES EMPLEADOR(IDEMPLEADOR)
);

-- Agenda
CREATE TABLE AGENDA (
    IDAGENDA INT PRIMARY KEY AUTO_INCREMENT,
    FECHAEXAMEN DATE NOT NULL,
    COMENTARIO TEXT NOT NULL,
    HORAEXAMEN TIME NOT NULL,
    IDSOLICITUD INT,
    FOREIGN KEY (IDSOLICITUD) REFERENCES SOLICITUD(IDSOLICITUD)
);

-- Agenda_Bateria
CREATE TABLE AGENDA_BATERIA (
    IDAGENDA INT,
    IDBATTERIA INT,
    PRIMARY KEY (IDAGENDA, IDBATTERIA),
    FOREIGN KEY (IDAGENDA) REFERENCES AGENDA(IDAGENDA),
    FOREIGN KEY (IDBATTERIA) REFERENCES BATERIA(IDBATTERIA)
);

-- Dashboard
CREATE TABLE DASHBOARD (
    IDDASHBOARD INT PRIMARY KEY AUTO_INCREMENT,
    TOTALBORRADOR INT NOT NULL,
    TOTALAPROBADA INT NOT NULL,
    TOTALRECHAZADA INT NOT NULL,
    TOTALPENDIENTE INT NOT NULL,
    TOTALAGENDADA INT NOT NULL,
    TOTALINICIADA INT NOT NULL,
    TOTALFINALIZADA INT NOT NULL,
    REGION VARCHAR(255) NOT NULL,
    COMUNA VARCHAR(255) NOT NULL,
    IDSOLICITUD INT,
    FOREIGN KEY (IDSOLICITUD) REFERENCES SOLICITUD(IDSOLICITUD)
);



-- Insert data into USUARIOS
INSERT INTO USUARIOS (RUT, NOMBRES, APELLIDOS, REGION, COMUNA, TIPO, EMAIL, FONO, CLAVE, VIGENTE) VALUES
('12345678-9', 'Juan', 'Perez', 'Metropolitana', 'Santiago', 'ADMIN', 'juan.perez@example.com', '123456789', 'password123', TRUE);

-- Insert data into PRESTADOR
INSERT INTO PRESTADOR (NOMBRE, DIRECCION, FONO, CONTACTO, CORREO, REGION, COMUNA, FECHAINICIO, FECHAFIN, VIGENTE) VALUES
('Prestador A', 'Direccion 123', '987654321', 'Contacto A', 'prestadorA@example.com', 'Metropolitana', 'Santiago', '2022-01-01', '2023-01-01', TRUE);

-- Insert data into EMPLEADOR
INSERT INTO EMPLEADOR (RUT, RAZONSOCIAL, CONTACTO, FONO, CORREO, TIPO, DIRECCION, REGION, COMUNA, CODIGOAEO, VIGENTE) VALUES
('98765432-1', 'Empresa XYZ', 'Contacto XYZ', '987654321', 'empresa.xyz@example.com', 'TIPO1', 'Direccion Empresa XYZ', 'Metropolitana', 'Santiago', 'AE123', TRUE);

-- Insert data into ARCHIVOS
INSERT INTO ARCHIVOS (NOMBRE, TIPO_ARCHIVO) VALUES
('Archivo 1', 'PDF'),
('Archivo 2', 'DOCX');

-- Insert data into TRABAJADOR
INSERT INTO TRABAJADOR (RUT, NOMBRES, APELLIDOS, VIGENTE, IDEMPLEADOR, ID_ARCHIVO) VALUES
('23456789-0', 'Maria', 'Gomez', TRUE, 1, 1);

-- Insert data into ESTADOS_SOLICITUD
INSERT INTO ESTADOS_SOLICITUD (NOMBRE_ESTADO, ESTADO) VALUES
('Pendiente', 'Activo'),
('Aprobada', 'Activo'),
('Rechazada', 'Inactivo');

-- Insert data into SOLICITUD
INSERT INTO SOLICITUD (FECHASOLICITUD, IDUSUARIO, IDEMPLEADOR, NOMBRE, RAZON, ESTADO, IDPRESTADOR, DIRECCION_PRESTADOR, ID_ESTADO, ID_ARCHIVO) VALUES
('2022-01-01', 1, 1, 'Solicitud 1', 'Razon 1', 'Pendiente', 1, 'Direccion Prestador 1', 1, 1);

-- Insert data into BATERIA
INSERT INTO BATERIA (NOMBRE, RECOMENDACION, JORNADA, VIGENTE, IDPRESTADOR) VALUES
('Bateria 1', 'Recomendacion 1', 'Jornada 1', TRUE, 1);

-- Insert data into EXAMENES
INSERT INTO EXAMENES (IDBATTERIA, NOMBRE, EVALUACION) VALUES
(1, 'Examen 1', 'Evaluacion 1');

-- Insert data into SOL_EMP_TRA
INSERT INTO SOL_EMP_TRA (IDSOLICITUD, IDEMPLEADOR, IDTRABAJADOR) VALUES
(1, 1, 1);

-- Insert data into COMENTARIOS_SOLICITUD
INSERT INTO COMENTARIOS_SOLICITUD (FECHACOMENTARIO, TEXTO, IDSOLICITUD) VALUES
('2022-01-02', 'Comentario de ejemplo', 1);

-- Insert data into SOLICITUD_TRABAJADOR_EXAMEN
INSERT INTO SOLICITUD_TRABAJADOR_EXAMEN (IDSOLICITUD, IDTRABAJADOR) VALUES
(1, 1);

-- Insert data into ACTIVIDADECONOMICA
INSERT INTO ACTIVIDADECONOMICA (CODIGOAE, DESCRIPCION, ESTADO) VALUES
('AE123', 'Descripcion Actividad Economica', 'Activo');

-- Insert data into AFILIACION
INSERT INTO AFILIACION (FECHACONSULTA, AFILIADO, IDEMPLEADOR) VALUES
('2022-01-03', TRUE, 1);

-- Insert data into AGENDA
INSERT INTO AGENDA (FECHAEXAMEN, COMENTARIO, HORAEXAMEN, IDSOLICITUD) VALUES
('2022-01-04', 'Comentario Agenda', '10:00:00', 1);

-- Insert data into AGENDA_BATERIA
INSERT INTO AGENDA_BATERIA (IDAGENDA, IDBATTERIA) VALUES
(1, 1);

-- Insert data into DASHBOARD
INSERT INTO DASHBOARD (TOTALBORRADOR, TOTALAPROBADA, TOTALRECHAZADA, TOTALPENDIENTE, TOTALAGENDADA, TOTALINICIADA, TOTALFINALIZADA, REGION, COMUNA, IDSOLICITUD) VALUES
(1, 1, 0, 1, 1, 0, 0, 'Metropolitana', 'Santiago', 1);
